import { NarrationLocationKey } from '../types/blue-test';

export const CHALLENGE_NARRATION_SCRIPTS: Record<NarrationLocationKey, {
  label: string;
  description: string;
  defaultScript: string;
  spokenScript?: string;
  isChallenge?: boolean;
}> = {
  'blue_test_challenge_01': {
    label: 'Challenge 1',
    description: 'Session 1 Q1 (Global Q1)',
    defaultScript: "Challenge 1 – T.D.T 0.3 seconds, get ready!",
    spokenScript: "Challenge 1 – T.D.T 0.3 seconds, get ready!",
    isChallenge: true,
  },
  'blue_test_challenge_02': {
    label: 'Challenge 2',
    description: 'Session 1 Q2 (Global Q2)',
    defaultScript: "Challenge 2 – T.D.T 0.5 seconds, get ready!",
    spokenScript: "Challenge 2 – T.D.T 0.5 seconds, get ready!",
    isChallenge: true,
  },
  'blue_test_challenge_03': {
    label: 'Challenge 3',
    description: 'Session 1 Q3 (Global Q3)',
    defaultScript: "Challenge 3 – T.D.T 0.8 seconds, get ready!",
    spokenScript: "Challenge 3 – T.D.T 0.8 seconds, get ready!",
    isChallenge: true,
  },
  'blue_test_challenge_04': {
    label: 'Challenge 4',
    description: 'Session 1 Q4 (Global Q4)',
    defaultScript: "Challenge 4 – T.D.T 1.1 seconds, get ready!",
    spokenScript: "Challenge 4 – T.D.T 1.1 seconds, get ready!",
    isChallenge: true,
  },
  'blue_test_challenge_05': {
    label: 'Challenge 5',
    description: 'Session 1 Q5 (Global Q5)',
    defaultScript: "Challenge 5 – T.D.T 1.3 seconds, get ready!",
    spokenScript: "Challenge 5 – T.D.T 1.3 seconds, get ready!",
    isChallenge: true,
  },
  'blue_test_challenge_06': {
    label: 'Challenge 6',
    description: 'Session 1 Q6 (Global Q6)',
    defaultScript: "Challenge 6 – T.D.T 1.6 seconds, get ready!",
    spokenScript: "Challenge 6 – T.D.T 1.6 seconds, get ready!",
    isChallenge: true,
  },
  'blue_test_challenge_07': {
    label: 'Challenge 7',
    description: 'Session 1 Q7 (Global Q7)',
    defaultScript: "Challenge 7 – T.D.T 1.86 seconds (Chunks Constant), get ready!",
    spokenScript: "Challenge 7 – T.D.T 1.86 seconds (Chunks Constant), get ready!",
    isChallenge: true,
  },
  'blue_test_challenge_08': {
    label: 'Challenge 8',
    description: 'Session 2 Q1 (Global Q8)',
    defaultScript: "Challenge 8 – T.D.T 2.1 seconds, get ready!",
    spokenScript: "Challenge 8 – T.D.T 2.1 seconds, get ready!",
    isChallenge: true,
  },
  'blue_test_challenge_09': {
    label: 'Challenge 9',
    description: 'Session 2 Q2 (Global Q9)',
    defaultScript: "Challenge 9 – T.D.T 2.3 seconds, get ready!",
    spokenScript: "Challenge 9 – T.D.T 2.3 seconds, get ready!",
    isChallenge: true,
  },
  'blue_test_challenge_10': {
    label: 'Challenge 10',
    description: 'Session 2 Q3 (Global Q10)',
    defaultScript: "Challenge 10 – T.D.T 2.5 seconds, get ready!",
    spokenScript: "Challenge 10 – T.D.T 2.5 seconds, get ready!",
    isChallenge: true,
  },
  'blue_test_challenge_11': {
    label: 'Challenge 11',
    description: 'Session 2 Q4 (Global Q11)',
    defaultScript: "Challenge 11 – T.D.T 2.8 seconds, get ready!",
    spokenScript: "Challenge 11 – T.D.T 2.8 seconds, get ready!",
    isChallenge: true,
  },
  'blue_test_challenge_12': {
    label: 'Challenge 12',
    description: 'Session 2 Q5 (Global Q12)',
    defaultScript: "Challenge 12 – T.D.T 3.0 seconds, get ready!",
    spokenScript: "Challenge 12 – T.D.T 3.0 seconds, get ready!",
    isChallenge: true,
  },
  'blue_test_challenge_13': {
    label: 'Challenge 13',
    description: 'Session 2 Q6 (Global Q13)',
    defaultScript: "Challenge 13 – T.D.T 3.2 seconds, get ready!",
    spokenScript: "Challenge 13 – T.D.T 3.2 seconds, get ready!",
    isChallenge: true,
  },
  'blue_test_challenge_14': {
    label: 'Challenge 14',
    description: 'Session 2 Q7 (Global Q14)',
    defaultScript: "Challenge 14 – T.D.T 3.5 seconds, get ready!",
    spokenScript: "Challenge 14 – T.D.T 3.5 seconds, get ready!",
    isChallenge: true,
  },
  'blue_test_challenge_15': {
    label: 'Challenge 15',
    description: 'Session 3 Q1 (Global Q15)',
    defaultScript: "Challenge 15 – T.D.T 3.9 seconds, get ready!",
    spokenScript: "Challenge 15 – T.D.T 3.9 seconds, get ready!",
    isChallenge: true,
  },
  'blue_test_challenge_16': {
    label: 'Challenge 16',
    description: 'Session 3 Q2 (Global Q16)',
    defaultScript: "Challenge 16 – T.D.T 4.3 seconds, get ready!",
    spokenScript: "Challenge 16 – T.D.T 4.3 seconds, get ready!",
    isChallenge: true,
  },
  'blue_test_challenge_17': {
    label: 'Challenge 17',
    description: 'Session 3 Q3 (Global Q17)',
    defaultScript: "Challenge 17 – T.D.T 4.7 seconds, get ready!",
    spokenScript: "Challenge 17 – T.D.T 4.7 seconds, get ready!",
    isChallenge: true,
  },
  'blue_test_challenge_18': {
    label: 'Challenge 18',
    description: 'Session 3 Q4 (Global Q18)',
    defaultScript: "Challenge 18 – T.D.T 5.2 seconds, get ready!",
    spokenScript: "Challenge 18 – T.D.T 5.2 seconds, get ready!",
    isChallenge: true,
  },
  'blue_test_challenge_19': {
    label: 'Challenge 19',
    description: 'Session 3 Q5 (Global Q19)',
    defaultScript: "Challenge 19 – T.D.T 5.6 seconds, get ready!",
    spokenScript: "Challenge 19 – T.D.T 5.6 seconds, get ready!",
    isChallenge: true,
  },
  'blue_test_challenge_20': {
    label: 'Challenge 20',
    description: 'Session 3 Q6 (Global Q20)',
    defaultScript: "Challenge 20 – T.D.T 6.0 seconds, get ready!",
    spokenScript: "Challenge 20 – T.D.T 6.0 seconds, get ready!",
    isChallenge: true,
  },
  'blue_test_challenge_21': {
    label: 'Challenge 21',
    description: 'Session 3 Q7 (Global Q21)',
    defaultScript: "Challenge 21 – T.D.T 6.4 seconds, get ready!",
    spokenScript: "Challenge 21 – T.D.T 6.4 seconds, get ready!",
    isChallenge: true,
  },
  'blue_test_challenge_22': {
    label: 'Challenge 22',
    description: 'Session 4 Q1 (Global Q22)',
    defaultScript: "Challenge 22 – T.D.T 7.2 seconds, get ready!",
    spokenScript: "Challenge 22 – T.D.T 7.2 seconds, get ready!",
    isChallenge: true,
  },
  'blue_test_challenge_23': {
    label: 'Challenge 23',
    description: 'Session 4 Q2 (Global Q23)',
    defaultScript: "Challenge 23 – T.D.T 8.0 seconds, get ready!",
    spokenScript: "Challenge 23 – T.D.T 8.0 seconds, get ready!",
    isChallenge: true,
  },
  'blue_test_challenge_24': {
    label: 'Challenge 24',
    description: 'Session 4 Q3 (Global Q24)',
    defaultScript: "Challenge 24 – T.D.T 8.8 seconds, get ready!",
    spokenScript: "Challenge 24 – T.D.T 8.8 seconds, get ready!",
    isChallenge: true,
  },
  'blue_test_challenge_25': {
    label: 'Challenge 25',
    description: 'Session 4 Q4 (Global Q25)',
    defaultScript: "Challenge 25 – T.D.T 9.6 seconds, get ready!",
    spokenScript: "Challenge 25 – T.D.T 9.6 seconds, get ready!",
    isChallenge: true,
  },
  'blue_test_challenge_26': {
    label: 'Challenge 26',
    description: 'Session 4 Q5 (Global Q26)',
    defaultScript: "Challenge 26 – T.D.T 10.4 seconds, get ready!",
    spokenScript: "Challenge 26 – T.D.T 10.4 seconds, get ready!",
    isChallenge: true,
  },
  'blue_test_challenge_27': {
    label: 'Challenge 27',
    description: 'Session 4 Q6 (Global Q27)',
    defaultScript: "Challenge 27 – T.D.T 11.2 seconds, get ready!",
    spokenScript: "Challenge 27 – T.D.T 11.2 seconds, get ready!",
    isChallenge: true,
  },
  'blue_test_challenge_28': {
    label: 'Challenge 28',
    description: 'Session 4 Q7 (Global Q28)',
    defaultScript: "Challenge 28 – T.D.T 12.0 seconds, get ready!",
    spokenScript: "Challenge 28 – T.D.T 12.0 seconds, get ready!",
    isChallenge: true,
  },
  'blue_test_challenge_29': {
    label: 'Challenge 29',
    description: 'Session 5 Q1 (Global Q29)',
    defaultScript: "Challenge 29 – T.D.T 13.4 seconds, get ready!",
    spokenScript: "Challenge 29 – T.D.T 13.4 seconds, get ready!",
    isChallenge: true,
  },
  'blue_test_challenge_30': {
    label: 'Challenge 30',
    description: 'Session 5 Q2 (Global Q30)',
    defaultScript: "Challenge 30 – T.D.T 14.9 seconds, get ready!",
    spokenScript: "Challenge 30 – T.D.T 14.9 seconds, get ready!",
    isChallenge: true,
  },
  'blue_test_challenge_31': {
    label: 'Challenge 31',
    description: 'Session 5 Q3 (Global Q31)',
    defaultScript: "Challenge 31 – T.D.T 16.4 seconds, get ready!",
    spokenScript: "Challenge 31 – T.D.T 16.4 seconds, get ready!",
    isChallenge: true,
  },
  'blue_test_challenge_32': {
    label: 'Challenge 32',
    description: 'Session 5 Q4 (Global Q32)',
    defaultScript: "Challenge 32 – T.D.T 17.9 seconds, get ready!",
    spokenScript: "Challenge 32 – T.D.T 17.9 seconds, get ready!",
    isChallenge: true,
  },
  'blue_test_challenge_33': {
    label: 'Challenge 33',
    description: 'Session 5 Q5 (Global Q33)',
    defaultScript: "Challenge 33 – T.D.T 19.3 seconds, get ready!",
    spokenScript: "Challenge 33 – T.D.T 19.3 seconds, get ready!",
    isChallenge: true,
  },
  'blue_test_challenge_34': {
    label: 'Challenge 34',
    description: 'Session 5 Q6 (Global Q34)',
    defaultScript: "Challenge 34 – T.D.T 20.8 seconds, get ready!",
    spokenScript: "Challenge 34 – T.D.T 20.8 seconds, get ready!",
    isChallenge: true,
  },
  'blue_test_challenge_35': {
    label: 'Challenge 35',
    description: 'Session 5 Q7 (Global Q35)',
    defaultScript: "Challenge 35 – T.D.T 22.3 seconds, get ready!",
    spokenScript: "Challenge 35 – T.D.T 22.3 seconds, get ready!",
    isChallenge: true,
  },
  'blue_test_challenge_36': {
    label: 'Challenge 36',
    description: 'Session 6 Q1 (Global Q36)',
    defaultScript: "Challenge 36 – T.D.T 25.0 seconds, get ready!",
    spokenScript: "Challenge 36 – T.D.T 25.0 seconds, get ready!",
    isChallenge: true,
  },
  'blue_test_challenge_37': {
    label: 'Challenge 37',
    description: 'Session 6 Q2 (Global Q37)',
    defaultScript: "Challenge 37 – T.D.T 27.7 seconds, get ready!",
    spokenScript: "Challenge 37 – T.D.T 27.7 seconds, get ready!",
    isChallenge: true,
  },
  'blue_test_challenge_38': {
    label: 'Challenge 38',
    description: 'Session 6 Q3 (Global Q38)',
    defaultScript: "Challenge 38 – T.D.T 30.5 seconds, get ready!",
    spokenScript: "Challenge 38 – T.D.T 30.5 seconds, get ready!",
    isChallenge: true,
  },
  'blue_test_challenge_39': {
    label: 'Challenge 39',
    description: 'Session 6 Q4 (Global Q39)',
    defaultScript: "Challenge 39 – T.D.T 33.2 seconds, get ready!",
    spokenScript: "Challenge 39 – T.D.T 33.2 seconds, get ready!",
    isChallenge: true,
  },
  'blue_test_challenge_40': {
    label: 'Challenge 40',
    description: 'Session 6 Q5 (Global Q40)',
    defaultScript: "Challenge 40 – T.D.T 35.9 seconds, get ready!",
    spokenScript: "Challenge 40 – T.D.T 35.9 seconds, get ready!",
    isChallenge: true,
  },
  'blue_test_challenge_41': {
    label: 'Challenge 41',
    description: 'Session 6 Q6 (Global Q41)',
    defaultScript: "Challenge 41 – T.D.T 38.7 seconds, get ready!",
    spokenScript: "Challenge 41 – T.D.T 38.7 seconds, get ready!",
    isChallenge: true,
  },
  'blue_test_challenge_42': {
    label: 'Challenge 42',
    description: 'Session 6 Q7 (Global Q42)',
    defaultScript: "Challenge 42 – T.D.T 41.4 seconds, get ready!",
    spokenScript: "Challenge 42 – T.D.T 41.4 seconds, get ready!",
    isChallenge: true,
  },
  'blue_test_challenge_43': {
    label: 'Challenge 43',
    description: 'Session 7 Q1 (Global Q43)',
    defaultScript: "Challenge 43 – T.D.T 46.5 seconds, get ready!",
    spokenScript: "Challenge 43 – T.D.T 46.5 seconds, get ready!",
    isChallenge: true,
  },
  'blue_test_challenge_44': {
    label: 'Challenge 44',
    description: 'Session 7 Q2 (Global Q44)',
    defaultScript: "Challenge 44 – T.D.T 51.6 seconds, get ready!",
    spokenScript: "Challenge 44 – T.D.T 51.6 seconds, get ready!",
    isChallenge: true,
  },
  'blue_test_challenge_45': {
    label: 'Challenge 45',
    description: 'Session 7 Q3 (Global Q45)',
    defaultScript: "Challenge 45 – T.D.T 56.7 seconds, get ready!",
    spokenScript: "Challenge 45 – T.D.T 56.7 seconds, get ready!",
    isChallenge: true,
  },
  'blue_test_challenge_46': {
    label: 'Challenge 46',
    description: 'Session 7 Q4 (Global Q46)',
    defaultScript: "Challenge 46 – T.D.T 61.8 seconds, get ready!",
    spokenScript: "Challenge 46 – T.D.T 61.8 seconds, get ready!",
    isChallenge: true,
  },
  'blue_test_challenge_47': {
    label: 'Challenge 47',
    description: 'Session 7 Q5 (Global Q47)',
    defaultScript: "Challenge 47 – T.D.T 66.8 seconds, get ready!",
    spokenScript: "Challenge 47 – T.D.T 66.8 seconds, get ready!",
    isChallenge: true,
  },
  'blue_test_challenge_48': {
    label: 'Challenge 48',
    description: 'Session 7 Q6 (Global Q48)',
    defaultScript: "Challenge 48 – T.D.T 71.9 seconds, get ready!",
    spokenScript: "Challenge 48 – T.D.T 71.9 seconds, get ready!",
    isChallenge: true,
  },
  'blue_test_challenge_49': {
    label: 'Challenge 49',
    description: 'Session 7 Q7 (Global Q49)',
    defaultScript: "Challenge 49 – T.D.T 77 seconds (Chunks Gate), get ready!",
    spokenScript: "Challenge 49 – T.D.T 77 seconds (Chunks Gate), get ready!",
    isChallenge: true,
  },
};
