import { NarrationLocationKey } from '../types/blue-test';

export const CHALLENGE_NARRATION_SCRIPTS: Record<NarrationLocationKey, {
  label: string;
  description: string;
  defaultScript: string;
  spokenScript?: string;
  isChallenge?: boolean;
}> = {
  'blue_test_challenge_01': {
    label: 'Challenge 1',
    description: 'Session 1 Q1 (Global Q1)',
    defaultScript: "Challenge 1 – CHUNKS Number — 1 – T.C.T 0.3 seconds – GET READY.",
    spokenScript: "Challenge one. CHUNKS NUMBER: ONE. T C T: 0.3 seconds. Get ready.",
    isChallenge: true,
  },
  'blue_test_challenge_02': {
    label: 'Challenge 2',
    description: 'Session 1 Q2 (Global Q2)',
    defaultScript: "Challenge 2 – CHUNKS Number — 1 – T.C.T 0.5 seconds – GET READY.",
    spokenScript: "Challenge two. CHUNKS NUMBER: ONE. T C T: 0.5 seconds. Get ready.",
    isChallenge: true,
  },
  'blue_test_challenge_03': {
    label: 'Challenge 3',
    description: 'Session 1 Q3 (Global Q3)',
    defaultScript: "Challenge 3 – CHUNKS Number — 1 – T.C.T 0.8 seconds – GET READY.",
    spokenScript: "Challenge three. CHUNKS NUMBER: ONE. T C T: 0.8 seconds. Get ready.",
    isChallenge: true,
  },
  'blue_test_challenge_04': {
    label: 'Challenge 4',
    description: 'Session 1 Q4 (Global Q4)',
    defaultScript: "Challenge 4 – CHUNKS Number — 1 – T.C.T 1.1 seconds – GET READY.",
    spokenScript: "Challenge four. CHUNKS NUMBER: ONE. T C T: 1.1 seconds. Get ready.",
    isChallenge: true,
  },
  'blue_test_challenge_05': {
    label: 'Challenge 5',
    description: 'Session 1 Q5 (Global Q5)',
    defaultScript: "Challenge 5 – CHUNKS Number — 1 – T.C.T 1.3 seconds – GET READY.",
    spokenScript: "Challenge five. CHUNKS NUMBER: ONE. T C T: 1.3 seconds. Get ready.",
    isChallenge: true,
  },
  'blue_test_challenge_06': {
    label: 'Challenge 6',
    description: 'Session 1 Q6 (Global Q6)',
    defaultScript: "Challenge 6 – CHUNKS Number — 1 – T.C.T 1.6 seconds – GET READY.",
    spokenScript: "Challenge six. CHUNKS NUMBER: ONE. T C T: 1.6 seconds. Get ready.",
    isChallenge: true,
  },
  'blue_test_challenge_07': {
    label: 'Challenge 7',
    description: 'Session 1 Q7 (Global Q7)',
    defaultScript: "Challenge 7 – CHUNKS Number — 1 – T.C.T 1.86 seconds – CHUNKS CONSTANT – GET READY.",
    spokenScript: "Challenge seven. CHUNKS NUMBER: ONE. T C T: 1.86 seconds. CHUNKS CONSTANT. Get ready.",
    isChallenge: true,
  },
  'blue_test_challenge_08': {
    label: 'Challenge 8',
    description: 'Session 2 Q1 (Global Q8)',
    defaultScript: "Challenge 8 – CHUNKS Number — 2 – T.C.T 2.1 seconds – GET READY.",
    spokenScript: "Challenge eight. CHUNKS NUMBER: TWO. T C T: 2.1 seconds. Get ready.",
    isChallenge: true,
  },
  'blue_test_challenge_09': {
    label: 'Challenge 9',
    description: 'Session 2 Q2 (Global Q9)',
    defaultScript: "Challenge 9 – CHUNKS Number — 2 – T.C.T 2.3 seconds – GET READY.",
    spokenScript: "Challenge nine. CHUNKS NUMBER: TWO. T C T: 2.3 seconds. Get ready.",
    isChallenge: true,
  },
  'blue_test_challenge_10': {
    label: 'Challenge 10',
    description: 'Session 2 Q3 (Global Q10)',
    defaultScript: "Challenge 10 – CHUNKS Number — 2 – T.C.T 2.5 seconds – GET READY.",
    spokenScript: "Challenge ten. CHUNKS NUMBER: TWO. T C T: 2.5 seconds. Get ready.",
    isChallenge: true,
  },
  'blue_test_challenge_11': {
    label: 'Challenge 11',
    description: 'Session 2 Q4 (Global Q11)',
    defaultScript: "Challenge 11 – CHUNKS Number — 2 – T.C.T 2.8 seconds – GET READY.",
    spokenScript: "Challenge eleven. CHUNKS NUMBER: TWO. T C T: 2.8 seconds. Get ready.",
    isChallenge: true,
  },
  'blue_test_challenge_12': {
    label: 'Challenge 12',
    description: 'Session 2 Q5 (Global Q12)',
    defaultScript: "Challenge 12 – CHUNKS Number — 2 – T.C.T 3.0 seconds – GET READY.",
    spokenScript: "Challenge twelve. CHUNKS NUMBER: TWO. T C T: 3.0 seconds. Get ready.",
    isChallenge: true,
  },
  'blue_test_challenge_13': {
    label: 'Challenge 13',
    description: 'Session 2 Q6 (Global Q13)',
    defaultScript: "Challenge 13 – CHUNKS Number — 2 – T.C.T 3.2 seconds – GET READY.",
    spokenScript: "Challenge thirteen. CHUNKS NUMBER: TWO. T C T: 3.2 seconds. Get ready.",
    isChallenge: true,
  },
  'blue_test_challenge_14': {
    label: 'Challenge 14',
    description: 'Session 2 Q7 (Global Q14)',
    defaultScript: "Challenge 14 – CHUNKS Number — 2 – T.C.T 3.5 seconds – GET READY.",
    spokenScript: "Challenge fourteen. CHUNKS NUMBER: TWO. T C T: 3.5 seconds. Get ready.",
    isChallenge: true,
  },
  'blue_test_challenge_15': {
    label: 'Challenge 15',
    description: 'Session 3 Q1 (Global Q15)',
    defaultScript: "Challenge 15 – CHUNKS Number — 3 – T.C.T 3.9 seconds – GET READY.",
    spokenScript: "Challenge fifteen. CHUNKS NUMBER: THREE. T C T: 3.9 seconds. Get ready.",
    isChallenge: true,
  },
  'blue_test_challenge_16': {
    label: 'Challenge 16',
    description: 'Session 3 Q2 (Global Q16)',
    defaultScript: "Challenge 16 – CHUNKS Number — 3 – T.C.T 4.3 seconds – GET READY.",
    spokenScript: "Challenge sixteen. CHUNKS NUMBER: THREE. T C T: 4.3 seconds. Get ready.",
    isChallenge: true,
  },
  'blue_test_challenge_17': {
    label: 'Challenge 17',
    description: 'Session 3 Q3 (Global Q17)',
    defaultScript: "Challenge 17 – CHUNKS Number — 3 – T.C.T 4.7 seconds – GET READY.",
    spokenScript: "Challenge seventeen. CHUNKS NUMBER: THREE. T C T: 4.7 seconds. Get ready.",
    isChallenge: true,
  },
  'blue_test_challenge_18': {
    label: 'Challenge 18',
    description: 'Session 3 Q4 (Global Q18)',
    defaultScript: "Challenge 18 – CHUNKS Number — 3 – T.C.T 5.2 seconds – GET READY.",
    spokenScript: "Challenge eighteen. CHUNKS NUMBER: THREE. T C T: 5.2 seconds. Get ready.",
    isChallenge: true,
  },
  'blue_test_challenge_19': {
    label: 'Challenge 19',
    description: 'Session 3 Q5 (Global Q19)',
    defaultScript: "Challenge 19 – CHUNKS Number — 3 – T.C.T 5.6 seconds – GET READY.",
    spokenScript: "Challenge nineteen. CHUNKS NUMBER: THREE. T C T: 5.6 seconds. Get ready.",
    isChallenge: true,
  },
  'blue_test_challenge_20': {
    label: 'Challenge 20',
    description: 'Session 3 Q6 (Global Q20)',
    defaultScript: "Challenge 20 – CHUNKS Number — 3 – T.C.T 6.0 seconds – GET READY.",
    spokenScript: "Challenge twenty. CHUNKS NUMBER: THREE. T C T: 6.0 seconds. Get ready.",
    isChallenge: true,
  },
  'blue_test_challenge_21': {
    label: 'Challenge 21',
    description: 'Session 3 Q7 (Global Q21)',
    defaultScript: "Challenge 21 – CHUNKS Number — 3 – T.C.T 6.4 seconds – GET READY.",
    spokenScript: "Challenge twenty-one. CHUNKS NUMBER: THREE. T C T: 6.4 seconds. Get ready.",
    isChallenge: true,
  },
  'blue_test_challenge_22': {
    label: 'Challenge 22',
    description: 'Session 4 Q1 (Global Q22)',
    defaultScript: "Challenge 22 – CHUNKS Number — 4 – T.C.T 7.2 seconds – GET READY.",
    spokenScript: "Challenge twenty-two. CHUNKS NUMBER: FOUR. T C T: 7.2 seconds. Get ready.",
    isChallenge: true,
  },
  'blue_test_challenge_23': {
    label: 'Challenge 23',
    description: 'Session 4 Q2 (Global Q23)',
    defaultScript: "Challenge 23 – CHUNKS Number — 4 – T.C.T 8.0 seconds – GET READY.",
    spokenScript: "Challenge twenty-three. CHUNKS NUMBER: FOUR. T C T: 8.0 seconds. Get ready.",
    isChallenge: true,
  },
  'blue_test_challenge_24': {
    label: 'Challenge 24',
    description: 'Session 4 Q3 (Global Q24)',
    defaultScript: "Challenge 24 – CHUNKS Number — 4 – T.C.T 8.8 seconds – GET READY.",
    spokenScript: "Challenge twenty-four. CHUNKS NUMBER: FOUR. T C T: 8.8 seconds. Get ready.",
    isChallenge: true,
  },
  'blue_test_challenge_25': {
    label: 'Challenge 25',
    description: 'Session 4 Q4 (Global Q25)',
    defaultScript: "Challenge 25 – CHUNKS Number — 4 – T.C.T 9.6 seconds – GET READY.",
    spokenScript: "Challenge twenty-five. CHUNKS NUMBER: FOUR. T C T: 9.6 seconds. Get ready.",
    isChallenge: true,
  },
  'blue_test_challenge_26': {
    label: 'Challenge 26',
    description: 'Session 4 Q5 (Global Q26)',
    defaultScript: "Challenge 26 – CHUNKS Number — 4 – T.C.T 10.4 seconds – GET READY.",
    spokenScript: "Challenge twenty-six. CHUNKS NUMBER: FOUR. T C T: 10.4 seconds. Get ready.",
    isChallenge: true,
  },
  'blue_test_challenge_27': {
    label: 'Challenge 27',
    description: 'Session 4 Q6 (Global Q27)',
    defaultScript: "Challenge 27 – CHUNKS Number — 4 – T.C.T 11.2 seconds – GET READY.",
    spokenScript: "Challenge twenty-seven. CHUNKS NUMBER: FOUR. T C T: 11.2 seconds. Get ready.",
    isChallenge: true,
  },
  'blue_test_challenge_28': {
    label: 'Challenge 28',
    description: 'Session 4 Q7 (Global Q28)',
    defaultScript: "Challenge 28 – CHUNKS Number — 4 – T.C.T 12.0 seconds – GET READY.",
    spokenScript: "Challenge twenty-eight. CHUNKS NUMBER: FOUR. T C T: 12.0 seconds. Get ready.",
    isChallenge: true,
  },
  'blue_test_challenge_29': {
    label: 'Challenge 29',
    description: 'Session 5 Q1 (Global Q29)',
    defaultScript: "Challenge 29 – CHUNKS Number — 5 – T.C.T 13.4 seconds – GET READY.",
    spokenScript: "Challenge twenty-nine. CHUNKS NUMBER: FIVE. T C T: 13.4 seconds. Get ready.",
    isChallenge: true,
  },
  'blue_test_challenge_30': {
    label: 'Challenge 30',
    description: 'Session 5 Q2 (Global Q30)',
    defaultScript: "Challenge 30 – CHUNKS Number — 5 – T.C.T 14.9 seconds – GET READY.",
    spokenScript: "Challenge thirty. CHUNKS NUMBER: FIVE. T C T: 14.9 seconds. Get ready.",
    isChallenge: true,
  },
  'blue_test_challenge_31': {
    label: 'Challenge 31',
    description: 'Session 5 Q3 (Global Q31)',
    defaultScript: "Challenge 31 – CHUNKS Number — 5 – T.C.T 16.4 seconds – GET READY.",
    spokenScript: "Challenge thirty-one. CHUNKS NUMBER: FIVE. T C T: 16.4 seconds. Get ready.",
    isChallenge: true,
  },
  'blue_test_challenge_32': {
    label: 'Challenge 32',
    description: 'Session 5 Q4 (Global Q32)',
    defaultScript: "Challenge 32 – CHUNKS Number — 5 – T.C.T 17.9 seconds – GET READY.",
    spokenScript: "Challenge thirty-two. CHUNKS NUMBER: FIVE. T C T: 17.9 seconds. Get ready.",
    isChallenge: true,
  },
  'blue_test_challenge_33': {
    label: 'Challenge 33',
    description: 'Session 5 Q5 (Global Q33)',
    defaultScript: "Challenge 33 – CHUNKS Number — 5 – T.C.T 19.3 seconds – GET READY.",
    spokenScript: "Challenge thirty-three. CHUNKS NUMBER: FIVE. T C T: 19.3 seconds. Get ready.",
    isChallenge: true,
  },
  'blue_test_challenge_34': {
    label: 'Challenge 34',
    description: 'Session 5 Q6 (Global Q34)',
    defaultScript: "Challenge 34 – CHUNKS Number — 5 – T.C.T 20.8 seconds – GET READY.",
    spokenScript: "Challenge thirty-four. CHUNKS NUMBER: FIVE. T C T: 20.8 seconds. Get ready.",
    isChallenge: true,
  },
  'blue_test_challenge_35': {
    label: 'Challenge 35',
    description: 'Session 5 Q7 (Global Q35)',
    defaultScript: "Challenge 35 – CHUNKS Number — 5 – T.C.T 22.3 seconds – GET READY.",
    spokenScript: "Challenge thirty-five. CHUNKS NUMBER: FIVE. T C T: 22.3 seconds. Get ready.",
    isChallenge: true,
  },
  'blue_test_challenge_36': {
    label: 'Challenge 36',
    description: 'Session 6 Q1 (Global Q36)',
    defaultScript: "Challenge 36 – CHUNKS Number — 6 – T.C.T 25.0 seconds – GET READY.",
    spokenScript: "Challenge thirty-six. CHUNKS NUMBER: SIX. T C T: 25.0 seconds. Get ready.",
    isChallenge: true,
  },
  'blue_test_challenge_37': {
    label: 'Challenge 37',
    description: 'Session 6 Q2 (Global Q37)',
    defaultScript: "Challenge 37 – CHUNKS Number — 6 – T.C.T 27.7 seconds – GET READY.",
    spokenScript: "Challenge thirty-seven. CHUNKS NUMBER: SIX. T C T: 27.7 seconds. Get ready.",
    isChallenge: true,
  },
  'blue_test_challenge_38': {
    label: 'Challenge 38',
    description: 'Session 6 Q3 (Global Q38)',
    defaultScript: "Challenge 38 – CHUNKS Number — 6 – T.C.T 30.5 seconds – GET READY.",
    spokenScript: "Challenge thirty-eight. CHUNKS NUMBER: SIX. T C T: 30.5 seconds. Get ready.",
    isChallenge: true,
  },
  'blue_test_challenge_39': {
    label: 'Challenge 39',
    description: 'Session 6 Q4 (Global Q39)',
    defaultScript: "Challenge 39 – CHUNKS Number — 6 – T.C.T 33.2 seconds – GET READY.",
    spokenScript: "Challenge thirty-nine. CHUNKS NUMBER: SIX. T C T: 33.2 seconds. Get ready.",
    isChallenge: true,
  },
  'blue_test_challenge_40': {
    label: 'Challenge 40',
    description: 'Session 6 Q5 (Global Q40)',
    defaultScript: "Challenge 40 – CHUNKS Number — 6 – T.C.T 35.9 seconds – GET READY.",
    spokenScript: "Challenge forty. CHUNKS NUMBER: SIX. T C T: 35.9 seconds. Get ready.",
    isChallenge: true,
  },
  'blue_test_challenge_41': {
    label: 'Challenge 41',
    description: 'Session 6 Q6 (Global Q41)',
    defaultScript: "Challenge 41 – CHUNKS Number — 6 – T.C.T 38.7 seconds – GET READY.",
    spokenScript: "Challenge forty-one. CHUNKS NUMBER: SIX. T C T: 38.7 seconds. Get ready.",
    isChallenge: true,
  },
  'blue_test_challenge_42': {
    label: 'Challenge 42',
    description: 'Session 6 Q7 (Global Q42)',
    defaultScript: "Challenge 42 – CHUNKS Number — 6 – T.C.T 41.4 seconds – GET READY.",
    spokenScript: "Challenge forty-two. CHUNKS NUMBER: SIX. T C T: 41.4 seconds. Get ready.",
    isChallenge: true,
  },
  'blue_test_challenge_43': {
    label: 'Challenge 43',
    description: 'Session 7 Q1 (Global Q43)',
    defaultScript: "Challenge 43 – CHUNKS Number — 7 – T.C.T 46.5 seconds – GET READY.",
    spokenScript: "Challenge forty-three. CHUNKS NUMBER: SEVEN. T C T: 46.5 seconds. Get ready.",
    isChallenge: true,
  },
  'blue_test_challenge_44': {
    label: 'Challenge 44',
    description: 'Session 7 Q2 (Global Q44)',
    defaultScript: "Challenge 44 – CHUNKS Number — 7 – T.C.T 51.6 seconds – GET READY.",
    spokenScript: "Challenge forty-four. CHUNKS NUMBER: SEVEN. T C T: 51.6 seconds. Get ready.",
    isChallenge: true,
  },
  'blue_test_challenge_45': {
    label: 'Challenge 45',
    description: 'Session 7 Q3 (Global Q45)',
    defaultScript: "Challenge 45 – CHUNKS Number — 7 – T.C.T 56.7 seconds – GET READY.",
    spokenScript: "Challenge forty-five. CHUNKS NUMBER: SEVEN. T C T: 56.7 seconds. Get ready.",
    isChallenge: true,
  },
  'blue_test_challenge_46': {
    label: 'Challenge 46',
    description: 'Session 7 Q4 (Global Q46)',
    defaultScript: "Challenge 46 – CHUNKS Number — 7 – T.C.T 61.8 seconds – GET READY.",
    spokenScript: "Challenge forty-six. CHUNKS NUMBER: SEVEN. T C T: 61.8 seconds. Get ready.",
    isChallenge: true,
  },
  'blue_test_challenge_47': {
    label: 'Challenge 47',
    description: 'Session 7 Q5 (Global Q47)',
    defaultScript: "Challenge 47 – CHUNKS Number — 7 – T.C.T 66.8 seconds – GET READY.",
    spokenScript: "Challenge forty-seven. CHUNKS NUMBER: SEVEN. T C T: 66.8 seconds. Get ready.",
    isChallenge: true,
  },
  'blue_test_challenge_48': {
    label: 'Challenge 48',
    description: 'Session 7 Q6 (Global Q48)',
    defaultScript: "Challenge 48 – CHUNKS Number — 7 – T.C.T 71.9 seconds – GET READY.",
    spokenScript: "Challenge forty-eight. CHUNKS NUMBER: SEVEN. T C T: 71.9 seconds. Get ready.",
    isChallenge: true,
  },
  'blue_test_challenge_49': {
    label: 'Challenge 49',
    description: 'Session 7 Q7 (Global Q49)',
    defaultScript: "Challenge 49 – CHUNKS Number — 1 – T.C.T 77 seconds – CHUNKS GATE – GET READY.",
    spokenScript: "Challenge forty-nine. CHUNKS NUMBER: ONE. T C T: 77 seconds. CHUNKS GATE. Get ready.",
    isChallenge: true,
  },
};
